### ISSUE TITLE
Play 2.4 support

### ISSUE THREAD

**Issue by eintopf** [swagger-api/swagger-play#5] opened 2015-08-12 11:38 UTC
Hi,

I try to integrate swagger in my Play 2.4 project. Unfortunately I get a "conflicting cross-version suffixes" error, since this swagger module is compiled for Scala 2.10 and my Play 2.4 project for 2.11. Is there a workaround available or some sort of ETA when Play 2.4 will be supported?

Best regards,
Bennet

**Comment by benmccann** [comment] 2015-11-05 02:43
Play is dropping support for Scala 2.10 in Play 2.5. The reason for dropping Scala 2.10 support is that Play has a new library dependency on scala-java8-compat, which is only available for Scala 2.11. This library makes it easy to convert from and to common Scala and Java8 types, and hence it’s valuable to simplify the Play core.

**Comment by benmccann** [comment] 2015-11-12 01:38
swagger-play is compiled for `2.11.6` by default I believe: https://github.com/swagger-api/swagger-play/blob/master/play-2.4/swagger-play2/build.sbt#L6

Did you build the version from source or use a previously released version? You may just need a new version published in which case this could be closed as a duplicate of https://github.com/swagger-api/swagger-play/issues/9

**Comment by josephearl** [comment] 2015-12-15 23:56
@eintopf did you get this working?

**Comment by benmccann** [comment] 2015-12-16 16:27
@fehguy I believe this can be closed now that we've released support for Play 2.4

**Closed as completed** 2015-12-16 16:57 UTC
